version: "3"

services: 
  ory-admin:
    #image: ghcr.io/josxha/ory_admin:latest
    build: ./OryAdmin
    ports:
      - "127.0.0.1:5256:8080"
    networks:
      - ory
    environment:
      - KRATOS_ADMIN_URL=http://ory-kratos-1:4434
      - KRATOS_PUBLIC_URL=http://ory-kratos-1:4433
      - HYDRA_ADMIN_URL=http://ory-hydra-1:4445
      - HYDRA_PUBLIC_URL=http://ory-hydra-1:4444
      - OATHKEEPER_API_URL=http://ory-oathkeeper-1:4456
      - KETO_READ_URL=http://ory-keto-1:4466
      - KETO_WRITE_URL=http://ory-keto-1:4467
      - ENABLED_SERVICES=kratos,hydra,oathkeeper,keto
  kratos-self-service:
    #image: ghcr.io/josxha/kratos_self_service:latest
    build: ./KratosSelfService
    ports:
      - "127.0.0.1:5110:3000"
    networks:
      - ory
    environment:
      - KRATOS_PUBLIC_URL=http://ory-kratos-1:4433
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433
      - HYDRA_ADMIN_URL=http://ory-hydra-1:4445
      - HYDRA_TRAITS_MAPPING=email:email,name.first:given_name,name.last:family_name
      - WEBSITE_TITLE=OryUI
      #- WEBSITE_LOGO_URI=https://example.com/logo.png

networks:
  ory:
    external: true