/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing AuthenticatorAssuranceLevel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticatorAssuranceLevelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthenticatorAssuranceLevel
        //private AuthenticatorAssuranceLevel instance;

        public AuthenticatorAssuranceLevelTests()
        {
            // TODO uncomment below to create an instance of AuthenticatorAssuranceLevel
            //instance = new AuthenticatorAssuranceLevel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticatorAssuranceLevel
        /// </summary>
        [Fact]
        public void AuthenticatorAssuranceLevelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthenticatorAssuranceLevel
            //Assert.IsType<AuthenticatorAssuranceLevel>(instance);
        }
    }
}
