/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing BatchPatchIdentitiesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchPatchIdentitiesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchPatchIdentitiesResponse
        //private BatchPatchIdentitiesResponse instance;

        public BatchPatchIdentitiesResponseTests()
        {
            // TODO uncomment below to create an instance of BatchPatchIdentitiesResponse
            //instance = new BatchPatchIdentitiesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchPatchIdentitiesResponse
        /// </summary>
        [Fact]
        public void BatchPatchIdentitiesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchPatchIdentitiesResponse
            //Assert.IsType<BatchPatchIdentitiesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Identities'
        /// </summary>
        [Fact]
        public void IdentitiesTest()
        {
            // TODO unit test for the property 'Identities'
        }
    }
}
