/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing ContinueWithRecoveryUi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContinueWithRecoveryUiTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContinueWithRecoveryUi
        //private ContinueWithRecoveryUi instance;

        public ContinueWithRecoveryUiTests()
        {
            // TODO uncomment below to create an instance of ContinueWithRecoveryUi
            //instance = new ContinueWithRecoveryUi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContinueWithRecoveryUi
        /// </summary>
        [Fact]
        public void ContinueWithRecoveryUiInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContinueWithRecoveryUi
            //Assert.IsType<ContinueWithRecoveryUi>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Fact]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }
    }
}
