/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing ContinueWithSettingsUi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContinueWithSettingsUiTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContinueWithSettingsUi
        //private ContinueWithSettingsUi instance;

        public ContinueWithSettingsUiTests()
        {
            // TODO uncomment below to create an instance of ContinueWithSettingsUi
            //instance = new ContinueWithSettingsUi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContinueWithSettingsUi
        /// </summary>
        [Fact]
        public void ContinueWithSettingsUiInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContinueWithSettingsUi
            //Assert.IsType<ContinueWithSettingsUi>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Fact]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }
    }
}
