/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateRecoveryCodeForIdentityBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRecoveryCodeForIdentityBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRecoveryCodeForIdentityBody
        //private CreateRecoveryCodeForIdentityBody instance;

        public CreateRecoveryCodeForIdentityBodyTests()
        {
            // TODO uncomment below to create an instance of CreateRecoveryCodeForIdentityBody
            //instance = new CreateRecoveryCodeForIdentityBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRecoveryCodeForIdentityBody
        /// </summary>
        [Fact]
        public void CreateRecoveryCodeForIdentityBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateRecoveryCodeForIdentityBody
            //Assert.IsType<CreateRecoveryCodeForIdentityBody>(instance);
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'IdentityId'
        /// </summary>
        [Fact]
        public void IdentityIdTest()
        {
            // TODO unit test for the property 'IdentityId'
        }
    }
}
