/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteMySessionsCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteMySessionsCountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteMySessionsCount
        //private DeleteMySessionsCount instance;

        public DeleteMySessionsCountTests()
        {
            // TODO uncomment below to create an instance of DeleteMySessionsCount
            //instance = new DeleteMySessionsCount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteMySessionsCount
        /// </summary>
        [Fact]
        public void DeleteMySessionsCountInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteMySessionsCount
            //Assert.IsType<DeleteMySessionsCount>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
