/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetVersion200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetVersion200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetVersion200Response
        //private GetVersion200Response instance;

        public GetVersion200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetVersion200Response
            //instance = new GetVersion200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetVersion200Response
        /// </summary>
        [Fact]
        public void GetVersion200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetVersion200Response
            //Assert.IsType<GetVersion200Response>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
