/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityWithCredentialsPassword
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityWithCredentialsPasswordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityWithCredentialsPassword
        //private IdentityWithCredentialsPassword instance;

        public IdentityWithCredentialsPasswordTests()
        {
            // TODO uncomment below to create an instance of IdentityWithCredentialsPassword
            //instance = new IdentityWithCredentialsPassword();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityWithCredentialsPassword
        /// </summary>
        [Fact]
        public void IdentityWithCredentialsPasswordInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityWithCredentialsPassword
            //Assert.IsType<IdentityWithCredentialsPassword>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
    }
}
