/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityCredentialsCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityCredentialsCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityCredentialsCode
        //private IdentityCredentialsCode instance;

        public IdentityCredentialsCodeTests()
        {
            // TODO uncomment below to create an instance of IdentityCredentialsCode
            //instance = new IdentityCredentialsCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityCredentialsCode
        /// </summary>
        [Fact]
        public void IdentityCredentialsCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityCredentialsCode
            //Assert.IsType<IdentityCredentialsCode>(instance);
        }

        /// <summary>
        /// Test the property 'AddressType'
        /// </summary>
        [Fact]
        public void AddressTypeTest()
        {
            // TODO unit test for the property 'AddressType'
        }

        /// <summary>
        /// Test the property 'UsedAt'
        /// </summary>
        [Fact]
        public void UsedAtTest()
        {
            // TODO unit test for the property 'UsedAt'
        }
    }
}
