/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentitySchemaContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentitySchemaContainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentitySchemaContainer
        //private IdentitySchemaContainer instance;

        public IdentitySchemaContainerTests()
        {
            // TODO uncomment below to create an instance of IdentitySchemaContainer
            //instance = new IdentitySchemaContainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentitySchemaContainer
        /// </summary>
        [Fact]
        public void IdentitySchemaContainerInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentitySchemaContainer
            //Assert.IsType<IdentitySchemaContainer>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
    }
}
