/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing Identity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Identity
        //private Identity instance;

        public IdentityTests()
        {
            // TODO uncomment below to create an instance of Identity
            //instance = new Identity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Identity
        /// </summary>
        [Fact]
        public void IdentityInstanceTest()
        {
            // TODO uncomment below to test "IsType" Identity
            //Assert.IsType<Identity>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Fact]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'MetadataAdmin'
        /// </summary>
        [Fact]
        public void MetadataAdminTest()
        {
            // TODO unit test for the property 'MetadataAdmin'
        }

        /// <summary>
        /// Test the property 'MetadataPublic'
        /// </summary>
        [Fact]
        public void MetadataPublicTest()
        {
            // TODO unit test for the property 'MetadataPublic'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'RecoveryAddresses'
        /// </summary>
        [Fact]
        public void RecoveryAddressesTest()
        {
            // TODO unit test for the property 'RecoveryAddresses'
        }

        /// <summary>
        /// Test the property 'SchemaId'
        /// </summary>
        [Fact]
        public void SchemaIdTest()
        {
            // TODO unit test for the property 'SchemaId'
        }

        /// <summary>
        /// Test the property 'SchemaUrl'
        /// </summary>
        [Fact]
        public void SchemaUrlTest()
        {
            // TODO unit test for the property 'SchemaUrl'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'StateChangedAt'
        /// </summary>
        [Fact]
        public void StateChangedAtTest()
        {
            // TODO unit test for the property 'StateChangedAt'
        }

        /// <summary>
        /// Test the property 'Traits'
        /// </summary>
        [Fact]
        public void TraitsTest()
        {
            // TODO unit test for the property 'Traits'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'VerifiableAddresses'
        /// </summary>
        [Fact]
        public void VerifiableAddressesTest()
        {
            // TODO unit test for the property 'VerifiableAddresses'
        }
    }
}
