/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityPatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityPatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityPatch
        //private IdentityPatch instance;

        public IdentityPatchTests()
        {
            // TODO uncomment below to create an instance of IdentityPatch
            //instance = new IdentityPatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityPatch
        /// </summary>
        [Fact]
        public void IdentityPatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityPatch
            //Assert.IsType<IdentityPatch>(instance);
        }

        /// <summary>
        /// Test the property 'Create'
        /// </summary>
        [Fact]
        public void CreateTest()
        {
            // TODO unit test for the property 'Create'
        }

        /// <summary>
        /// Test the property 'PatchId'
        /// </summary>
        [Fact]
        public void PatchIdTest()
        {
            // TODO unit test for the property 'PatchId'
        }
    }
}
