/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityWithCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityWithCredentialsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityWithCredentials
        //private IdentityWithCredentials instance;

        public IdentityWithCredentialsTests()
        {
            // TODO uncomment below to create an instance of IdentityWithCredentials
            //instance = new IdentityWithCredentials();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityWithCredentials
        /// </summary>
        [Fact]
        public void IdentityWithCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityWithCredentials
            //Assert.IsType<IdentityWithCredentials>(instance);
        }

        /// <summary>
        /// Test the property 'Oidc'
        /// </summary>
        [Fact]
        public void OidcTest()
        {
            // TODO unit test for the property 'Oidc'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
