/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing PerformNativeLogoutBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PerformNativeLogoutBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PerformNativeLogoutBody
        //private PerformNativeLogoutBody instance;

        public PerformNativeLogoutBodyTests()
        {
            // TODO uncomment below to create an instance of PerformNativeLogoutBody
            //instance = new PerformNativeLogoutBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PerformNativeLogoutBody
        /// </summary>
        [Fact]
        public void PerformNativeLogoutBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PerformNativeLogoutBody
            //Assert.IsType<PerformNativeLogoutBody>(instance);
        }

        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Fact]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }
    }
}
