/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing SelfServiceFlowExpiredError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SelfServiceFlowExpiredErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SelfServiceFlowExpiredError
        //private SelfServiceFlowExpiredError instance;

        public SelfServiceFlowExpiredErrorTests()
        {
            // TODO uncomment below to create an instance of SelfServiceFlowExpiredError
            //instance = new SelfServiceFlowExpiredError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SelfServiceFlowExpiredError
        /// </summary>
        [Fact]
        public void SelfServiceFlowExpiredErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" SelfServiceFlowExpiredError
            //Assert.IsType<SelfServiceFlowExpiredError>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'ExpiredAt'
        /// </summary>
        [Fact]
        public void ExpiredAtTest()
        {
            // TODO unit test for the property 'ExpiredAt'
        }

        /// <summary>
        /// Test the property 'Since'
        /// </summary>
        [Fact]
        public void SinceTest()
        {
            // TODO unit test for the property 'Since'
        }

        /// <summary>
        /// Test the property 'UseFlowId'
        /// </summary>
        [Fact]
        public void UseFlowIdTest()
        {
            // TODO unit test for the property 'UseFlowId'
        }
    }
}
