/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing SuccessfulCodeExchangeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuccessfulCodeExchangeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuccessfulCodeExchangeResponse
        //private SuccessfulCodeExchangeResponse instance;

        public SuccessfulCodeExchangeResponseTests()
        {
            // TODO uncomment below to create an instance of SuccessfulCodeExchangeResponse
            //instance = new SuccessfulCodeExchangeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuccessfulCodeExchangeResponse
        /// </summary>
        [Fact]
        public void SuccessfulCodeExchangeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuccessfulCodeExchangeResponse
            //Assert.IsType<SuccessfulCodeExchangeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }

        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Fact]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }
    }
}
