/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateRecoveryFlowWithCodeMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRecoveryFlowWithCodeMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRecoveryFlowWithCodeMethod
        //private UpdateRecoveryFlowWithCodeMethod instance;

        public UpdateRecoveryFlowWithCodeMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateRecoveryFlowWithCodeMethod
            //instance = new UpdateRecoveryFlowWithCodeMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRecoveryFlowWithCodeMethod
        /// </summary>
        [Fact]
        public void UpdateRecoveryFlowWithCodeMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateRecoveryFlowWithCodeMethod
            //Assert.IsType<UpdateRecoveryFlowWithCodeMethod>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
    }
}
