/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateRegistrationFlowWithWebAuthnMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRegistrationFlowWithWebAuthnMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRegistrationFlowWithWebAuthnMethod
        //private UpdateRegistrationFlowWithWebAuthnMethod instance;

        public UpdateRegistrationFlowWithWebAuthnMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateRegistrationFlowWithWebAuthnMethod
            //instance = new UpdateRegistrationFlowWithWebAuthnMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRegistrationFlowWithWebAuthnMethod
        /// </summary>
        [Fact]
        public void UpdateRegistrationFlowWithWebAuthnMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateRegistrationFlowWithWebAuthnMethod
            //Assert.IsType<UpdateRegistrationFlowWithWebAuthnMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Traits'
        /// </summary>
        [Fact]
        public void TraitsTest()
        {
            // TODO unit test for the property 'Traits'
        }

        /// <summary>
        /// Test the property 'TransientPayload'
        /// </summary>
        [Fact]
        public void TransientPayloadTest()
        {
            // TODO unit test for the property 'TransientPayload'
        }

        /// <summary>
        /// Test the property 'WebauthnRegister'
        /// </summary>
        [Fact]
        public void WebauthnRegisterTest()
        {
            // TODO unit test for the property 'WebauthnRegister'
        }

        /// <summary>
        /// Test the property 'WebauthnRegisterDisplayname'
        /// </summary>
        [Fact]
        public void WebauthnRegisterDisplaynameTest()
        {
            // TODO unit test for the property 'WebauthnRegisterDisplayname'
        }
    }
}
