/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateRegistrationFlowWithPasswordMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRegistrationFlowWithPasswordMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRegistrationFlowWithPasswordMethod
        //private UpdateRegistrationFlowWithPasswordMethod instance;

        public UpdateRegistrationFlowWithPasswordMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateRegistrationFlowWithPasswordMethod
            //instance = new UpdateRegistrationFlowWithPasswordMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRegistrationFlowWithPasswordMethod
        /// </summary>
        [Fact]
        public void UpdateRegistrationFlowWithPasswordMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateRegistrationFlowWithPasswordMethod
            //Assert.IsType<UpdateRegistrationFlowWithPasswordMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Traits'
        /// </summary>
        [Fact]
        public void TraitsTest()
        {
            // TODO unit test for the property 'Traits'
        }

        /// <summary>
        /// Test the property 'TransientPayload'
        /// </summary>
        [Fact]
        public void TransientPayloadTest()
        {
            // TODO unit test for the property 'TransientPayload'
        }
    }
}
