/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateLoginFlowWithWebAuthnMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateLoginFlowWithWebAuthnMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateLoginFlowWithWebAuthnMethod
        //private UpdateLoginFlowWithWebAuthnMethod instance;

        public UpdateLoginFlowWithWebAuthnMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateLoginFlowWithWebAuthnMethod
            //instance = new UpdateLoginFlowWithWebAuthnMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateLoginFlowWithWebAuthnMethod
        /// </summary>
        [Fact]
        public void UpdateLoginFlowWithWebAuthnMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateLoginFlowWithWebAuthnMethod
            //Assert.IsType<UpdateLoginFlowWithWebAuthnMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'WebauthnLogin'
        /// </summary>
        [Fact]
        public void WebauthnLoginTest()
        {
            // TODO unit test for the property 'WebauthnLogin'
        }
    }
}
