/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateLoginFlowWithOidcMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateLoginFlowWithOidcMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateLoginFlowWithOidcMethod
        //private UpdateLoginFlowWithOidcMethod instance;

        public UpdateLoginFlowWithOidcMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateLoginFlowWithOidcMethod
            //instance = new UpdateLoginFlowWithOidcMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateLoginFlowWithOidcMethod
        /// </summary>
        [Fact]
        public void UpdateLoginFlowWithOidcMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateLoginFlowWithOidcMethod
            //Assert.IsType<UpdateLoginFlowWithOidcMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'IdToken'
        /// </summary>
        [Fact]
        public void IdTokenTest()
        {
            // TODO unit test for the property 'IdToken'
        }

        /// <summary>
        /// Test the property 'IdTokenNonce'
        /// </summary>
        [Fact]
        public void IdTokenNonceTest()
        {
            // TODO unit test for the property 'IdTokenNonce'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Traits'
        /// </summary>
        [Fact]
        public void TraitsTest()
        {
            // TODO unit test for the property 'Traits'
        }

        /// <summary>
        /// Test the property 'UpstreamParameters'
        /// </summary>
        [Fact]
        public void UpstreamParametersTest()
        {
            // TODO unit test for the property 'UpstreamParameters'
        }
    }
}
