/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateVerificationFlowWithLinkMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateVerificationFlowWithLinkMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateVerificationFlowWithLinkMethod
        //private UpdateVerificationFlowWithLinkMethod instance;

        public UpdateVerificationFlowWithLinkMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateVerificationFlowWithLinkMethod
            //instance = new UpdateVerificationFlowWithLinkMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateVerificationFlowWithLinkMethod
        /// </summary>
        [Fact]
        public void UpdateVerificationFlowWithLinkMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateVerificationFlowWithLinkMethod
            //Assert.IsType<UpdateVerificationFlowWithLinkMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
    }
}
