/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing VerifiableIdentityAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifiableIdentityAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifiableIdentityAddress
        //private VerifiableIdentityAddress instance;

        public VerifiableIdentityAddressTests()
        {
            // TODO uncomment below to create an instance of VerifiableIdentityAddress
            //instance = new VerifiableIdentityAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifiableIdentityAddress
        /// </summary>
        [Fact]
        public void VerifiableIdentityAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifiableIdentityAddress
            //Assert.IsType<VerifiableIdentityAddress>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Fact]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }

        /// <summary>
        /// Test the property 'VerifiedAt'
        /// </summary>
        [Fact]
        public void VerifiedAtTest()
        {
            // TODO unit test for the property 'VerifiedAt'
        }

        /// <summary>
        /// Test the property 'Via'
        /// </summary>
        [Fact]
        public void ViaTest()
        {
            // TODO unit test for the property 'Via'
        }
    }
}
