/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ory.Kratos.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Ory.Kratos.Client.Model
{
    /// <summary>
    /// Update Registration Request Body
    /// </summary>
    [JsonConverter(typeof(UpdateRegistrationFlowBodyJsonConverter))]
    [DataContract(Name = "updateRegistrationFlowBody")]
    public partial class UpdateRegistrationFlowBody : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRegistrationFlowBody" /> class
        /// with the <see cref="UpdateRegistrationFlowWithPasswordMethod" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of UpdateRegistrationFlowWithPasswordMethod.</param>
        public UpdateRegistrationFlowBody(UpdateRegistrationFlowWithPasswordMethod actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRegistrationFlowBody" /> class
        /// with the <see cref="UpdateRegistrationFlowWithOidcMethod" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of UpdateRegistrationFlowWithOidcMethod.</param>
        public UpdateRegistrationFlowBody(UpdateRegistrationFlowWithOidcMethod actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRegistrationFlowBody" /> class
        /// with the <see cref="UpdateRegistrationFlowWithWebAuthnMethod" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of UpdateRegistrationFlowWithWebAuthnMethod.</param>
        public UpdateRegistrationFlowBody(UpdateRegistrationFlowWithWebAuthnMethod actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRegistrationFlowBody" /> class
        /// with the <see cref="UpdateRegistrationFlowWithCodeMethod" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of UpdateRegistrationFlowWithCodeMethod.</param>
        public UpdateRegistrationFlowBody(UpdateRegistrationFlowWithCodeMethod actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(UpdateRegistrationFlowWithCodeMethod))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(UpdateRegistrationFlowWithOidcMethod))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(UpdateRegistrationFlowWithPasswordMethod))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(UpdateRegistrationFlowWithWebAuthnMethod))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: UpdateRegistrationFlowWithCodeMethod, UpdateRegistrationFlowWithOidcMethod, UpdateRegistrationFlowWithPasswordMethod, UpdateRegistrationFlowWithWebAuthnMethod");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `UpdateRegistrationFlowWithPasswordMethod`. If the actual instance is not `UpdateRegistrationFlowWithPasswordMethod`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of UpdateRegistrationFlowWithPasswordMethod</returns>
        public UpdateRegistrationFlowWithPasswordMethod GetUpdateRegistrationFlowWithPasswordMethod()
        {
            return (UpdateRegistrationFlowWithPasswordMethod)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `UpdateRegistrationFlowWithOidcMethod`. If the actual instance is not `UpdateRegistrationFlowWithOidcMethod`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of UpdateRegistrationFlowWithOidcMethod</returns>
        public UpdateRegistrationFlowWithOidcMethod GetUpdateRegistrationFlowWithOidcMethod()
        {
            return (UpdateRegistrationFlowWithOidcMethod)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `UpdateRegistrationFlowWithWebAuthnMethod`. If the actual instance is not `UpdateRegistrationFlowWithWebAuthnMethod`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of UpdateRegistrationFlowWithWebAuthnMethod</returns>
        public UpdateRegistrationFlowWithWebAuthnMethod GetUpdateRegistrationFlowWithWebAuthnMethod()
        {
            return (UpdateRegistrationFlowWithWebAuthnMethod)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `UpdateRegistrationFlowWithCodeMethod`. If the actual instance is not `UpdateRegistrationFlowWithCodeMethod`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of UpdateRegistrationFlowWithCodeMethod</returns>
        public UpdateRegistrationFlowWithCodeMethod GetUpdateRegistrationFlowWithCodeMethod()
        {
            return (UpdateRegistrationFlowWithCodeMethod)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateRegistrationFlowBody {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, UpdateRegistrationFlowBody.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of UpdateRegistrationFlowBody
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of UpdateRegistrationFlowBody</returns>
        public static UpdateRegistrationFlowBody FromJson(string jsonString)
        {
            UpdateRegistrationFlowBody newUpdateRegistrationFlowBody = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newUpdateRegistrationFlowBody;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(UpdateRegistrationFlowWithCodeMethod).GetProperty("AdditionalProperties") == null)
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithCodeMethod>(jsonString, UpdateRegistrationFlowBody.SerializerSettings));
                }
                else
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithCodeMethod>(jsonString, UpdateRegistrationFlowBody.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("UpdateRegistrationFlowWithCodeMethod");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into UpdateRegistrationFlowWithCodeMethod: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(UpdateRegistrationFlowWithOidcMethod).GetProperty("AdditionalProperties") == null)
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithOidcMethod>(jsonString, UpdateRegistrationFlowBody.SerializerSettings));
                }
                else
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithOidcMethod>(jsonString, UpdateRegistrationFlowBody.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("UpdateRegistrationFlowWithOidcMethod");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into UpdateRegistrationFlowWithOidcMethod: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(UpdateRegistrationFlowWithPasswordMethod).GetProperty("AdditionalProperties") == null)
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithPasswordMethod>(jsonString, UpdateRegistrationFlowBody.SerializerSettings));
                }
                else
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithPasswordMethod>(jsonString, UpdateRegistrationFlowBody.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("UpdateRegistrationFlowWithPasswordMethod");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into UpdateRegistrationFlowWithPasswordMethod: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(UpdateRegistrationFlowWithWebAuthnMethod).GetProperty("AdditionalProperties") == null)
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithWebAuthnMethod>(jsonString, UpdateRegistrationFlowBody.SerializerSettings));
                }
                else
                {
                    newUpdateRegistrationFlowBody = new UpdateRegistrationFlowBody(JsonConvert.DeserializeObject<UpdateRegistrationFlowWithWebAuthnMethod>(jsonString, UpdateRegistrationFlowBody.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("UpdateRegistrationFlowWithWebAuthnMethod");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into UpdateRegistrationFlowWithWebAuthnMethod: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newUpdateRegistrationFlowBody;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for UpdateRegistrationFlowBody
    /// </summary>
    public class UpdateRegistrationFlowBodyJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(UpdateRegistrationFlowBody).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return UpdateRegistrationFlowBody.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return UpdateRegistrationFlowBody.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
