/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HealthNotReadyStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthNotReadyStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthNotReadyStatus
        //private HealthNotReadyStatus instance;

        public HealthNotReadyStatusTests()
        {
            // TODO uncomment below to create an instance of HealthNotReadyStatus
            //instance = new HealthNotReadyStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthNotReadyStatus
        /// </summary>
        [Fact]
        public void HealthNotReadyStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthNotReadyStatus
            //Assert.IsType<HealthNotReadyStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
