/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityPatchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityPatchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityPatchResponse
        //private IdentityPatchResponse instance;

        public IdentityPatchResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityPatchResponse
            //instance = new IdentityPatchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityPatchResponse
        /// </summary>
        [Fact]
        public void IdentityPatchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityPatchResponse
            //Assert.IsType<IdentityPatchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Identity'
        /// </summary>
        [Fact]
        public void IdentityTest()
        {
            // TODO unit test for the property 'Identity'
        }

        /// <summary>
        /// Test the property 'PatchId'
        /// </summary>
        [Fact]
        public void PatchIdTest()
        {
            // TODO unit test for the property 'PatchId'
        }
    }
}
