/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityWithCredentialsPasswordConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityWithCredentialsPasswordConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityWithCredentialsPasswordConfig
        //private IdentityWithCredentialsPasswordConfig instance;

        public IdentityWithCredentialsPasswordConfigTests()
        {
            // TODO uncomment below to create an instance of IdentityWithCredentialsPasswordConfig
            //instance = new IdentityWithCredentialsPasswordConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityWithCredentialsPasswordConfig
        /// </summary>
        [Fact]
        public void IdentityWithCredentialsPasswordConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityWithCredentialsPasswordConfig
            //Assert.IsType<IdentityWithCredentialsPasswordConfig>(instance);
        }

        /// <summary>
        /// Test the property 'HashedPassword'
        /// </summary>
        [Fact]
        public void HashedPasswordTest()
        {
            // TODO unit test for the property 'HashedPassword'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
