/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityWithCredentialsOidcConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityWithCredentialsOidcConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityWithCredentialsOidcConfig
        //private IdentityWithCredentialsOidcConfig instance;

        public IdentityWithCredentialsOidcConfigTests()
        {
            // TODO uncomment below to create an instance of IdentityWithCredentialsOidcConfig
            //instance = new IdentityWithCredentialsOidcConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityWithCredentialsOidcConfig
        /// </summary>
        [Fact]
        public void IdentityWithCredentialsOidcConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityWithCredentialsOidcConfig
            //Assert.IsType<IdentityWithCredentialsOidcConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'Providers'
        /// </summary>
        [Fact]
        public void ProvidersTest()
        {
            // TODO unit test for the property 'Providers'
        }
    }
}
