/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing LogoutFlow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogoutFlowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogoutFlow
        //private LogoutFlow instance;

        public LogoutFlowTests()
        {
            // TODO uncomment below to create an instance of LogoutFlow
            //instance = new LogoutFlow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogoutFlow
        /// </summary>
        [Fact]
        public void LogoutFlowInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogoutFlow
            //Assert.IsType<LogoutFlow>(instance);
        }

        /// <summary>
        /// Test the property 'LogoutToken'
        /// </summary>
        [Fact]
        public void LogoutTokenTest()
        {
            // TODO unit test for the property 'LogoutToken'
        }

        /// <summary>
        /// Test the property 'LogoutUrl'
        /// </summary>
        [Fact]
        public void LogoutUrlTest()
        {
            // TODO unit test for the property 'LogoutUrl'
        }
    }
}
