/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UiNodeImageAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UiNodeImageAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UiNodeImageAttributes
        //private UiNodeImageAttributes instance;

        public UiNodeImageAttributesTests()
        {
            // TODO uncomment below to create an instance of UiNodeImageAttributes
            //instance = new UiNodeImageAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UiNodeImageAttributes
        /// </summary>
        [Fact]
        public void UiNodeImageAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" UiNodeImageAttributes
            //Assert.IsType<UiNodeImageAttributes>(instance);
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'NodeType'
        /// </summary>
        [Fact]
        public void NodeTypeTest()
        {
            // TODO unit test for the property 'NodeType'
        }

        /// <summary>
        /// Test the property 'Src'
        /// </summary>
        [Fact]
        public void SrcTest()
        {
            // TODO unit test for the property 'Src'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
    }
}
