/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ContinueWith
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContinueWithTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContinueWith
        //private ContinueWith instance;

        public ContinueWithTests()
        {
            // TODO uncomment below to create an instance of ContinueWith
            //instance = new ContinueWith();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContinueWith
        /// </summary>
        [Fact]
        public void ContinueWithInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContinueWith
            //Assert.IsType<ContinueWith>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Fact]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }

        /// <summary>
        /// Test the property 'OrySessionToken'
        /// </summary>
        [Fact]
        public void OrySessionTokenTest()
        {
            // TODO unit test for the property 'OrySessionToken'
        }
    }
}
