/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityWithCredentialsOidc
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityWithCredentialsOidcTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityWithCredentialsOidc
        //private IdentityWithCredentialsOidc instance;

        public IdentityWithCredentialsOidcTests()
        {
            // TODO uncomment below to create an instance of IdentityWithCredentialsOidc
            //instance = new IdentityWithCredentialsOidc();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityWithCredentialsOidc
        /// </summary>
        [Fact]
        public void IdentityWithCredentialsOidcInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityWithCredentialsOidc
            //Assert.IsType<IdentityWithCredentialsOidc>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
    }
}
