/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NeedsPrivilegedSessionError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NeedsPrivilegedSessionErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NeedsPrivilegedSessionError
        //private NeedsPrivilegedSessionError instance;

        public NeedsPrivilegedSessionErrorTests()
        {
            // TODO uncomment below to create an instance of NeedsPrivilegedSessionError
            //instance = new NeedsPrivilegedSessionError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NeedsPrivilegedSessionError
        /// </summary>
        [Fact]
        public void NeedsPrivilegedSessionErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" NeedsPrivilegedSessionError
            //Assert.IsType<NeedsPrivilegedSessionError>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'RedirectBrowserTo'
        /// </summary>
        [Fact]
        public void RedirectBrowserToTest()
        {
            // TODO unit test for the property 'RedirectBrowserTo'
        }
    }
}
