/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RecoveryLinkForIdentity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecoveryLinkForIdentityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecoveryLinkForIdentity
        //private RecoveryLinkForIdentity instance;

        public RecoveryLinkForIdentityTests()
        {
            // TODO uncomment below to create an instance of RecoveryLinkForIdentity
            //instance = new RecoveryLinkForIdentity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecoveryLinkForIdentity
        /// </summary>
        [Fact]
        public void RecoveryLinkForIdentityInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecoveryLinkForIdentity
            //Assert.IsType<RecoveryLinkForIdentity>(instance);
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'RecoveryLink'
        /// </summary>
        [Fact]
        public void RecoveryLinkTest()
        {
            // TODO unit test for the property 'RecoveryLink'
        }
    }
}
