/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SuccessfulNativeRegistration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuccessfulNativeRegistrationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuccessfulNativeRegistration
        //private SuccessfulNativeRegistration instance;

        public SuccessfulNativeRegistrationTests()
        {
            // TODO uncomment below to create an instance of SuccessfulNativeRegistration
            //instance = new SuccessfulNativeRegistration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuccessfulNativeRegistration
        /// </summary>
        [Fact]
        public void SuccessfulNativeRegistrationInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuccessfulNativeRegistration
            //Assert.IsType<SuccessfulNativeRegistration>(instance);
        }

        /// <summary>
        /// Test the property 'ContinueWith'
        /// </summary>
        [Fact]
        public void ContinueWithTest()
        {
            // TODO unit test for the property 'ContinueWith'
        }

        /// <summary>
        /// Test the property 'Identity'
        /// </summary>
        [Fact]
        public void IdentityTest()
        {
            // TODO unit test for the property 'Identity'
        }

        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }

        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Fact]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }
    }
}
