/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateSettingsFlowWithWebAuthnMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSettingsFlowWithWebAuthnMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateSettingsFlowWithWebAuthnMethod
        //private UpdateSettingsFlowWithWebAuthnMethod instance;

        public UpdateSettingsFlowWithWebAuthnMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateSettingsFlowWithWebAuthnMethod
            //instance = new UpdateSettingsFlowWithWebAuthnMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateSettingsFlowWithWebAuthnMethod
        /// </summary>
        [Fact]
        public void UpdateSettingsFlowWithWebAuthnMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateSettingsFlowWithWebAuthnMethod
            //Assert.IsType<UpdateSettingsFlowWithWebAuthnMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'WebauthnRegister'
        /// </summary>
        [Fact]
        public void WebauthnRegisterTest()
        {
            // TODO unit test for the property 'WebauthnRegister'
        }

        /// <summary>
        /// Test the property 'WebauthnRegisterDisplayname'
        /// </summary>
        [Fact]
        public void WebauthnRegisterDisplaynameTest()
        {
            // TODO unit test for the property 'WebauthnRegisterDisplayname'
        }

        /// <summary>
        /// Test the property 'WebauthnRemove'
        /// </summary>
        [Fact]
        public void WebauthnRemoveTest()
        {
            // TODO unit test for the property 'WebauthnRemove'
        }
    }
}
