/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateSettingsFlowWithPasswordMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSettingsFlowWithPasswordMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateSettingsFlowWithPasswordMethod
        //private UpdateSettingsFlowWithPasswordMethod instance;

        public UpdateSettingsFlowWithPasswordMethodTests()
        {
            // TODO uncomment below to create an instance of UpdateSettingsFlowWithPasswordMethod
            //instance = new UpdateSettingsFlowWithPasswordMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateSettingsFlowWithPasswordMethod
        /// </summary>
        [Fact]
        public void UpdateSettingsFlowWithPasswordMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateSettingsFlowWithPasswordMethod
            //Assert.IsType<UpdateSettingsFlowWithPasswordMethod>(instance);
        }

        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
