/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing AcceptOAuth2LoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcceptOAuth2LoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcceptOAuth2LoginRequest
        //private AcceptOAuth2LoginRequest instance;

        public AcceptOAuth2LoginRequestTests()
        {
            // TODO uncomment below to create an instance of AcceptOAuth2LoginRequest
            //instance = new AcceptOAuth2LoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcceptOAuth2LoginRequest
        /// </summary>
        [Fact]
        public void AcceptOAuth2LoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcceptOAuth2LoginRequest
            //Assert.IsType<AcceptOAuth2LoginRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Acr'
        /// </summary>
        [Fact]
        public void AcrTest()
        {
            // TODO unit test for the property 'Acr'
        }

        /// <summary>
        /// Test the property 'Amr'
        /// </summary>
        [Fact]
        public void AmrTest()
        {
            // TODO unit test for the property 'Amr'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'ExtendSessionLifespan'
        /// </summary>
        [Fact]
        public void ExtendSessionLifespanTest()
        {
            // TODO unit test for the property 'ExtendSessionLifespan'
        }

        /// <summary>
        /// Test the property 'ForceSubjectIdentifier'
        /// </summary>
        [Fact]
        public void ForceSubjectIdentifierTest()
        {
            // TODO unit test for the property 'ForceSubjectIdentifier'
        }

        /// <summary>
        /// Test the property 'IdentityProviderSessionId'
        /// </summary>
        [Fact]
        public void IdentityProviderSessionIdTest()
        {
            // TODO unit test for the property 'IdentityProviderSessionId'
        }

        /// <summary>
        /// Test the property 'Remember'
        /// </summary>
        [Fact]
        public void RememberTest()
        {
            // TODO unit test for the property 'Remember'
        }

        /// <summary>
        /// Test the property 'RememberFor'
        /// </summary>
        [Fact]
        public void RememberForTest()
        {
            // TODO unit test for the property 'RememberFor'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
    }
}
