/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing AcceptOAuth2ConsentRequestSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcceptOAuth2ConsentRequestSessionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcceptOAuth2ConsentRequestSession
        //private AcceptOAuth2ConsentRequestSession instance;

        public AcceptOAuth2ConsentRequestSessionTests()
        {
            // TODO uncomment below to create an instance of AcceptOAuth2ConsentRequestSession
            //instance = new AcceptOAuth2ConsentRequestSession();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcceptOAuth2ConsentRequestSession
        /// </summary>
        [Fact]
        public void AcceptOAuth2ConsentRequestSessionInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcceptOAuth2ConsentRequestSession
            //Assert.IsType<AcceptOAuth2ConsentRequestSession>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'IdToken'
        /// </summary>
        [Fact]
        public void IdTokenTest()
        {
            // TODO unit test for the property 'IdToken'
        }
    }
}
