/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateJsonWebKeySet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateJsonWebKeySetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateJsonWebKeySet
        //private CreateJsonWebKeySet instance;

        public CreateJsonWebKeySetTests()
        {
            // TODO uncomment below to create an instance of CreateJsonWebKeySet
            //instance = new CreateJsonWebKeySet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateJsonWebKeySet
        /// </summary>
        [Fact]
        public void CreateJsonWebKeySetInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateJsonWebKeySet
            //Assert.IsType<CreateJsonWebKeySet>(instance);
        }

        /// <summary>
        /// Test the property 'Alg'
        /// </summary>
        [Fact]
        public void AlgTest()
        {
            // TODO unit test for the property 'Alg'
        }

        /// <summary>
        /// Test the property 'Kid'
        /// </summary>
        [Fact]
        public void KidTest()
        {
            // TODO unit test for the property 'Kid'
        }

        /// <summary>
        /// Test the property 'Use'
        /// </summary>
        [Fact]
        public void UseTest()
        {
            // TODO unit test for the property 'Use'
        }
    }
}
