/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing CredentialSupportedDraft00
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CredentialSupportedDraft00Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CredentialSupportedDraft00
        //private CredentialSupportedDraft00 instance;

        public CredentialSupportedDraft00Tests()
        {
            // TODO uncomment below to create an instance of CredentialSupportedDraft00
            //instance = new CredentialSupportedDraft00();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CredentialSupportedDraft00
        /// </summary>
        [Fact]
        public void CredentialSupportedDraft00InstanceTest()
        {
            // TODO uncomment below to test "IsType" CredentialSupportedDraft00
            //Assert.IsType<CredentialSupportedDraft00>(instance);
        }

        /// <summary>
        /// Test the property 'CryptographicBindingMethodsSupported'
        /// </summary>
        [Fact]
        public void CryptographicBindingMethodsSupportedTest()
        {
            // TODO unit test for the property 'CryptographicBindingMethodsSupported'
        }

        /// <summary>
        /// Test the property 'CryptographicSuitesSupported'
        /// </summary>
        [Fact]
        public void CryptographicSuitesSupportedTest()
        {
            // TODO unit test for the property 'CryptographicSuitesSupported'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Fact]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }
    }
}
