/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorOAuth2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorOAuth2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorOAuth2
        //private ErrorOAuth2 instance;

        public ErrorOAuth2Tests()
        {
            // TODO uncomment below to create an instance of ErrorOAuth2
            //instance = new ErrorOAuth2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorOAuth2
        /// </summary>
        [Fact]
        public void ErrorOAuth2InstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorOAuth2
            //Assert.IsType<ErrorOAuth2>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'ErrorDebug'
        /// </summary>
        [Fact]
        public void ErrorDebugTest()
        {
            // TODO unit test for the property 'ErrorDebug'
        }

        /// <summary>
        /// Test the property 'ErrorDescription'
        /// </summary>
        [Fact]
        public void ErrorDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDescription'
        }

        /// <summary>
        /// Test the property 'ErrorHint'
        /// </summary>
        [Fact]
        public void ErrorHintTest()
        {
            // TODO unit test for the property 'ErrorHint'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
