/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IntrospectedOAuth2Token
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IntrospectedOAuth2TokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IntrospectedOAuth2Token
        //private IntrospectedOAuth2Token instance;

        public IntrospectedOAuth2TokenTests()
        {
            // TODO uncomment below to create an instance of IntrospectedOAuth2Token
            //instance = new IntrospectedOAuth2Token();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IntrospectedOAuth2Token
        /// </summary>
        [Fact]
        public void IntrospectedOAuth2TokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" IntrospectedOAuth2Token
            //Assert.IsType<IntrospectedOAuth2Token>(instance);
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Aud'
        /// </summary>
        [Fact]
        public void AudTest()
        {
            // TODO unit test for the property 'Aud'
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Exp'
        /// </summary>
        [Fact]
        public void ExpTest()
        {
            // TODO unit test for the property 'Exp'
        }

        /// <summary>
        /// Test the property 'Ext'
        /// </summary>
        [Fact]
        public void ExtTest()
        {
            // TODO unit test for the property 'Ext'
        }

        /// <summary>
        /// Test the property 'Iat'
        /// </summary>
        [Fact]
        public void IatTest()
        {
            // TODO unit test for the property 'Iat'
        }

        /// <summary>
        /// Test the property 'Iss'
        /// </summary>
        [Fact]
        public void IssTest()
        {
            // TODO unit test for the property 'Iss'
        }

        /// <summary>
        /// Test the property 'Nbf'
        /// </summary>
        [Fact]
        public void NbfTest()
        {
            // TODO unit test for the property 'Nbf'
        }

        /// <summary>
        /// Test the property 'ObfuscatedSubject'
        /// </summary>
        [Fact]
        public void ObfuscatedSubjectTest()
        {
            // TODO unit test for the property 'ObfuscatedSubject'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'Sub'
        /// </summary>
        [Fact]
        public void SubTest()
        {
            // TODO unit test for the property 'Sub'
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

        /// <summary>
        /// Test the property 'TokenUse'
        /// </summary>
        [Fact]
        public void TokenUseTest()
        {
            // TODO unit test for the property 'TokenUse'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
    }
}
