/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing IsReady200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IsReady200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IsReady200Response
        //private IsReady200Response instance;

        public IsReady200ResponseTests()
        {
            // TODO uncomment below to create an instance of IsReady200Response
            //instance = new IsReady200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IsReady200Response
        /// </summary>
        [Fact]
        public void IsReady200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IsReady200Response
            //Assert.IsType<IsReady200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
