/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing OAuth2ConsentSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuth2ConsentSessionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuth2ConsentSession
        //private OAuth2ConsentSession instance;

        public OAuth2ConsentSessionTests()
        {
            // TODO uncomment below to create an instance of OAuth2ConsentSession
            //instance = new OAuth2ConsentSession();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuth2ConsentSession
        /// </summary>
        [Fact]
        public void OAuth2ConsentSessionInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuth2ConsentSession
            //Assert.IsType<OAuth2ConsentSession>(instance);
        }

        /// <summary>
        /// Test the property 'ConsentRequest'
        /// </summary>
        [Fact]
        public void ConsentRequestTest()
        {
            // TODO unit test for the property 'ConsentRequest'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'GrantAccessTokenAudience'
        /// </summary>
        [Fact]
        public void GrantAccessTokenAudienceTest()
        {
            // TODO unit test for the property 'GrantAccessTokenAudience'
        }

        /// <summary>
        /// Test the property 'GrantScope'
        /// </summary>
        [Fact]
        public void GrantScopeTest()
        {
            // TODO unit test for the property 'GrantScope'
        }

        /// <summary>
        /// Test the property 'HandledAt'
        /// </summary>
        [Fact]
        public void HandledAtTest()
        {
            // TODO unit test for the property 'HandledAt'
        }

        /// <summary>
        /// Test the property 'Remember'
        /// </summary>
        [Fact]
        public void RememberTest()
        {
            // TODO unit test for the property 'Remember'
        }

        /// <summary>
        /// Test the property 'RememberFor'
        /// </summary>
        [Fact]
        public void RememberForTest()
        {
            // TODO unit test for the property 'RememberFor'
        }

        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }
    }
}
