/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing OAuth2RedirectTo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuth2RedirectToTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuth2RedirectTo
        //private OAuth2RedirectTo instance;

        public OAuth2RedirectToTests()
        {
            // TODO uncomment below to create an instance of OAuth2RedirectTo
            //instance = new OAuth2RedirectTo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuth2RedirectTo
        /// </summary>
        [Fact]
        public void OAuth2RedirectToInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuth2RedirectTo
            //Assert.IsType<OAuth2RedirectTo>(instance);
        }

        /// <summary>
        /// Test the property 'RedirectTo'
        /// </summary>
        [Fact]
        public void RedirectToTest()
        {
            // TODO unit test for the property 'RedirectTo'
        }
    }
}
