/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing OAuth2LogoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuth2LogoutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuth2LogoutRequest
        //private OAuth2LogoutRequest instance;

        public OAuth2LogoutRequestTests()
        {
            // TODO uncomment below to create an instance of OAuth2LogoutRequest
            //instance = new OAuth2LogoutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuth2LogoutRequest
        /// </summary>
        [Fact]
        public void OAuth2LogoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuth2LogoutRequest
            //Assert.IsType<OAuth2LogoutRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Challenge'
        /// </summary>
        [Fact]
        public void ChallengeTest()
        {
            // TODO unit test for the property 'Challenge'
        }

        /// <summary>
        /// Test the property 'VarClient'
        /// </summary>
        [Fact]
        public void VarClientTest()
        {
            // TODO unit test for the property 'VarClient'
        }

        /// <summary>
        /// Test the property 'RequestUrl'
        /// </summary>
        [Fact]
        public void RequestUrlTest()
        {
            // TODO unit test for the property 'RequestUrl'
        }

        /// <summary>
        /// Test the property 'RpInitiated'
        /// </summary>
        [Fact]
        public void RpInitiatedTest()
        {
            // TODO unit test for the property 'RpInitiated'
        }

        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Fact]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
    }
}
