/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing OAuth2ConsentSessionExpiresAt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuth2ConsentSessionExpiresAtTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuth2ConsentSessionExpiresAt
        //private OAuth2ConsentSessionExpiresAt instance;

        public OAuth2ConsentSessionExpiresAtTests()
        {
            // TODO uncomment below to create an instance of OAuth2ConsentSessionExpiresAt
            //instance = new OAuth2ConsentSessionExpiresAt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuth2ConsentSessionExpiresAt
        /// </summary>
        [Fact]
        public void OAuth2ConsentSessionExpiresAtInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuth2ConsentSessionExpiresAt
            //Assert.IsType<OAuth2ConsentSessionExpiresAt>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'AuthorizeCode'
        /// </summary>
        [Fact]
        public void AuthorizeCodeTest()
        {
            // TODO unit test for the property 'AuthorizeCode'
        }

        /// <summary>
        /// Test the property 'IdToken'
        /// </summary>
        [Fact]
        public void IdTokenTest()
        {
            // TODO unit test for the property 'IdToken'
        }

        /// <summary>
        /// Test the property 'ParContext'
        /// </summary>
        [Fact]
        public void ParContextTest()
        {
            // TODO unit test for the property 'ParContext'
        }

        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Fact]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }
    }
}
