/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing OidcUserInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OidcUserInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OidcUserInfo
        //private OidcUserInfo instance;

        public OidcUserInfoTests()
        {
            // TODO uncomment below to create an instance of OidcUserInfo
            //instance = new OidcUserInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OidcUserInfo
        /// </summary>
        [Fact]
        public void OidcUserInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OidcUserInfo
            //Assert.IsType<OidcUserInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Birthdate'
        /// </summary>
        [Fact]
        public void BirthdateTest()
        {
            // TODO unit test for the property 'Birthdate'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }

        /// <summary>
        /// Test the property 'FamilyName'
        /// </summary>
        [Fact]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'GivenName'
        /// </summary>
        [Fact]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Fact]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Fact]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'PhoneNumberVerified'
        /// </summary>
        [Fact]
        public void PhoneNumberVerifiedTest()
        {
            // TODO unit test for the property 'PhoneNumberVerified'
        }

        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Fact]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }

        /// <summary>
        /// Test the property 'PreferredUsername'
        /// </summary>
        [Fact]
        public void PreferredUsernameTest()
        {
            // TODO unit test for the property 'PreferredUsername'
        }

        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }

        /// <summary>
        /// Test the property 'Sub'
        /// </summary>
        [Fact]
        public void SubTest()
        {
            // TODO unit test for the property 'Sub'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'Zoneinfo'
        /// </summary>
        [Fact]
        public void ZoneinfoTest()
        {
            // TODO unit test for the property 'Zoneinfo'
        }
    }
}
