/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing RFC6749ErrorJson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RFC6749ErrorJsonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RFC6749ErrorJson
        //private RFC6749ErrorJson instance;

        public RFC6749ErrorJsonTests()
        {
            // TODO uncomment below to create an instance of RFC6749ErrorJson
            //instance = new RFC6749ErrorJson();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RFC6749ErrorJson
        /// </summary>
        [Fact]
        public void RFC6749ErrorJsonInstanceTest()
        {
            // TODO uncomment below to test "IsType" RFC6749ErrorJson
            //Assert.IsType<RFC6749ErrorJson>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'ErrorDebug'
        /// </summary>
        [Fact]
        public void ErrorDebugTest()
        {
            // TODO unit test for the property 'ErrorDebug'
        }

        /// <summary>
        /// Test the property 'ErrorDescription'
        /// </summary>
        [Fact]
        public void ErrorDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDescription'
        }

        /// <summary>
        /// Test the property 'ErrorHint'
        /// </summary>
        [Fact]
        public void ErrorHintTest()
        {
            // TODO unit test for the property 'ErrorHint'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
