/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing TokenPaginationResponseHeaders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenPaginationResponseHeadersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenPaginationResponseHeaders
        //private TokenPaginationResponseHeaders instance;

        public TokenPaginationResponseHeadersTests()
        {
            // TODO uncomment below to create an instance of TokenPaginationResponseHeaders
            //instance = new TokenPaginationResponseHeaders();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenPaginationResponseHeaders
        /// </summary>
        [Fact]
        public void TokenPaginationResponseHeadersInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenPaginationResponseHeaders
            //Assert.IsType<TokenPaginationResponseHeaders>(instance);
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

        /// <summary>
        /// Test the property 'XTotalCount'
        /// </summary>
        [Fact]
        public void XTotalCountTest()
        {
            // TODO unit test for the property 'XTotalCount'
        }
    }
}
