/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing TrustOAuth2JwtGrantIssuer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrustOAuth2JwtGrantIssuerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrustOAuth2JwtGrantIssuer
        //private TrustOAuth2JwtGrantIssuer instance;

        public TrustOAuth2JwtGrantIssuerTests()
        {
            // TODO uncomment below to create an instance of TrustOAuth2JwtGrantIssuer
            //instance = new TrustOAuth2JwtGrantIssuer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrustOAuth2JwtGrantIssuer
        /// </summary>
        [Fact]
        public void TrustOAuth2JwtGrantIssuerInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrustOAuth2JwtGrantIssuer
            //Assert.IsType<TrustOAuth2JwtGrantIssuer>(instance);
        }

        /// <summary>
        /// Test the property 'AllowAnySubject'
        /// </summary>
        [Fact]
        public void AllowAnySubjectTest()
        {
            // TODO unit test for the property 'AllowAnySubject'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }

        /// <summary>
        /// Test the property 'Jwk'
        /// </summary>
        [Fact]
        public void JwkTest()
        {
            // TODO unit test for the property 'Jwk'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
    }
}
