/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing TrustedOAuth2JwtGrantJsonWebKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrustedOAuth2JwtGrantJsonWebKeyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrustedOAuth2JwtGrantJsonWebKey
        //private TrustedOAuth2JwtGrantJsonWebKey instance;

        public TrustedOAuth2JwtGrantJsonWebKeyTests()
        {
            // TODO uncomment below to create an instance of TrustedOAuth2JwtGrantJsonWebKey
            //instance = new TrustedOAuth2JwtGrantJsonWebKey();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrustedOAuth2JwtGrantJsonWebKey
        /// </summary>
        [Fact]
        public void TrustedOAuth2JwtGrantJsonWebKeyInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrustedOAuth2JwtGrantJsonWebKey
            //Assert.IsType<TrustedOAuth2JwtGrantJsonWebKey>(instance);
        }

        /// <summary>
        /// Test the property 'Kid'
        /// </summary>
        [Fact]
        public void KidTest()
        {
            // TODO unit test for the property 'Kid'
        }

        /// <summary>
        /// Test the property 'Set'
        /// </summary>
        [Fact]
        public void SetTest()
        {
            // TODO unit test for the property 'Set'
        }
    }
}
