/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing VerifiableCredentialProof
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifiableCredentialProofTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifiableCredentialProof
        //private VerifiableCredentialProof instance;

        public VerifiableCredentialProofTests()
        {
            // TODO uncomment below to create an instance of VerifiableCredentialProof
            //instance = new VerifiableCredentialProof();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifiableCredentialProof
        /// </summary>
        [Fact]
        public void VerifiableCredentialProofInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifiableCredentialProof
            //Assert.IsType<VerifiableCredentialProof>(instance);
        }

        /// <summary>
        /// Test the property 'Jwt'
        /// </summary>
        [Fact]
        public void JwtTest()
        {
            // TODO unit test for the property 'Jwt'
        }

        /// <summary>
        /// Test the property 'ProofType'
        /// </summary>
        [Fact]
        public void ProofTypeTest()
        {
            // TODO unit test for the property 'ProofType'
        }
    }
}
