/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Client.Model;
using Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Client.Test.Model
{
    /// <summary>
    ///  Class for testing VerifiableCredentialResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifiableCredentialResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifiableCredentialResponse
        //private VerifiableCredentialResponse instance;

        public VerifiableCredentialResponseTests()
        {
            // TODO uncomment below to create an instance of VerifiableCredentialResponse
            //instance = new VerifiableCredentialResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifiableCredentialResponse
        /// </summary>
        [Fact]
        public void VerifiableCredentialResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifiableCredentialResponse
            //Assert.IsType<VerifiableCredentialResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CredentialDraft00'
        /// </summary>
        [Fact]
        public void CredentialDraft00Test()
        {
            // TODO unit test for the property 'CredentialDraft00'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
    }
}
